# Generated by Django 2.2 on 2023-07-08 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cid', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ord_id', models.CharField(max_length=20)),
                ('date', models.CharField(max_length=50)),
                ('status', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=200)),
                ('spare_part_id', models.CharField(max_length=200)),
                ('quantity', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pid', models.CharField(max_length=20)),
                ('ord_id', models.CharField(max_length=50)),
                ('date', models.CharField(max_length=200)),
                ('payment_method', models.CharField(max_length=200)),
                ('amount', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='shipping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sid', models.CharField(max_length=20)),
                ('ord_id', models.CharField(max_length=50)),
                ('shipping_date', models.CharField(max_length=200)),
                ('estimated_delivery_date', models.CharField(max_length=200)),
                ('shipping_address', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='spare_part',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spare_part_id', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=50)),
                ('number', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=200)),
                ('quantity_available', models.CharField(max_length=200)),
                ('supplier_id', models.CharField(max_length=200)),
                ('price', models.CharField(max_length=200)),
                ('company', models.CharField(max_length=200)),
                ('photo', models.FileField(upload_to='documents/')),
            ],
        ),
        migrations.CreateModel(
            name='supplier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sid', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=50)),
                ('contact', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=200)),
                ('spare_part_name', models.CharField(max_length=200)),
                ('company', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='UserLogin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=40)),
                ('password', models.CharField(max_length=50)),
                ('utype', models.CharField(max_length=50)),
            ],
        ),
    ]
